#端口配置
server:
  port: 8088
  servlet:
    context-path: /

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://118.31.187.222:3306/szcp_project?allowMultiQueries=true
    username: szcp
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#如果数据为空的字段，则该字段省略不显示，可以通过添加配置文件，规定查询数据为空是则返回null。
mybatis:
  configuration:
    call-setters-on-nulls: true







